<h1>Introduction to TensorFlow</h1>

In [1]:
# importing tensorflow

import tensorflow as tf

In [7]:
tf.compat.v1.disable_eager_execution()

In [8]:
# to check the version of tensorflow using
print("Version of tensorflow: ", tf.__version__)

Version of tensorflow:  2.7.0


Tensor - simply means n-dimensional array

In [2]:
# playing with constants
# constants are the basic tensors available
hello = tf.constant("Hello")    
world = tf.constant("World")

In [3]:
type(hello)     # we see that this doesn't print the contents of the tensor

tensorflow.python.framework.ops.EagerTensor

In [7]:
hello.numpy()

b'Hello'

In [4]:
# concatenation
tf.print(hello+world)   # prints the contents of the constants/tensors

HelloWorld


In [12]:
# for addition of 2 numbers

a = tf.constant(10)
b = tf.constant(1)

tf.print(a+b)

<tf.Operation 'PrintV2_1' type=PrintV2>

In [13]:
with tf.compat.v1.Session() as sess:  
    print(sess.run(hello+world))

b'HelloWorld'


In [14]:
# So, to compute/print the tensors we need to run it under a Session

with tf.compat.v1.Session() as sess:
    hello = tf.constant("Hello") 
    world = tf.constant("World")   
    print(sess.run(hello+world))

b'HelloWorld'


<h2>Different tensors available to create</h2>

In [15]:
# creating constants

const = tf.constant(10)

In [16]:
# creating matrix filled with scalar values

fill_mat = tf.fill((3,3),10)    # creates a tensor filled with scalar values of dimensions specified
tf.print(fill_mat)

<tf.Operation 'PrintV2_2' type=PrintV2>

In [17]:
# Creating a null matrix

null_mat = tf.zeros((3,3))
tf.print(null_mat)

<tf.Operation 'PrintV2_3' type=PrintV2>

In [18]:
# creating a ones matrix
ones_mat = tf.ones((3,3))
tf.print(ones_mat)

<tf.Operation 'PrintV2_4' type=PrintV2>

In [19]:
# creating a tensor filled with random values of normal distribution
randn = tf.random.normal((3,3),mean=1,stddev=1.5)   # we specify the mean and standard deviation the values to be generated from
tf.print(randn)

<tf.Operation 'PrintV2_5' type=PrintV2>

In [20]:
# creating a tensor filled with random values of uniform distribution
randu = tf.random.uniform((3,3),minval=0,maxval=1)  # we specify the range between min and max value for random number to be generated
tf.print(randu)

<tf.Operation 'PrintV2_6' type=PrintV2>

In [21]:
sess = tf.compat.v1.InteractiveSession()

In [22]:
my_ops = [const, fill_mat, null_mat, ones_mat, randn, randu]
for op in my_ops:
    print(sess.run(op))
    print("\n")

10


[[10 10 10]
 [10 10 10]
 [10 10 10]]


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


[[ 2.459766    0.12824059 -0.6721699 ]
 [ 4.1958275   1.6642165   0.45715904]
 [ 3.0148897   1.808645    0.9952977 ]]


[[0.25765288 0.33422637 0.27154422]
 [0.71380854 0.9065243  0.57832813]
 [0.02766907 0.19157505 0.94844306]]




In [23]:
# matrix multiplication

a = tf.constant([[1,2],
                [3,4]])
                
b = tf.constant([[10],[100]])

In [26]:
print(a.get_shape())
print(b.get_shape())

(2, 2)
(2, 1)


In [27]:
result = tf.matmul(a,b)
sess.run(result)

array([[210],
       [430]])