<h1>Operations performed in numpy

In [1]:
import numpy as np

In [2]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
print(np.ndim(a))

1


<h3>reshape():- it changes the arrangement of items by changing the order

In [4]:
b = a.reshape(2,6)
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [5]:
print(b.ndim)

2


<h3>flatten()/ ravel():- it used for flattening, for converting n-dim to 1-d

In [6]:
x1 = b.flatten()
x1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [7]:
x2 = b.ravel()
x2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [8]:
# now let's replace 1st element 0 with 100 in b
b[0][0] = 100
b

array([[100,   1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10,  11]])

In [9]:
print(x1)  # flatten() is creating a copy
print(x2)  # ravel() is creating a view

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[100   1   2   3   4   5   6   7   8   9  10  11]


In [10]:
print(np.may_share_memory(x1,b))   # flatten() is creating a copy
print(np.may_share_memory(x2,b))   # ravel() is creating a view

False
True


In [11]:
# flatten method takes a parameter called order, by default it's row major
print(b, "\n")
print(b.flatten(order="f"))
print(b.flatten(order="c"))

[[100   1   2   3   4   5]
 [  6   7   8   9  10  11]] 

[100   6   1   7   2   8   3   9   4  10   5  11]
[100   1   2   3   4   5   6   7   8   9  10  11]


<h3>Stacking:- several arrays can be stacked together along different axes

np.vstack():- to stack arrays along vertical axis

np.hstack():- to stack arrays along horinzontal axis

In [12]:
x1 = np.array([[1,2],[3,4]])
x2 = np.array([[5,6],[7,8]])
np.vstack((x1,x2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [13]:
np.hstack((x1,x2))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

<h3>Matrix operations

In [27]:
x1 = np.array([[1,2],[3,4],[5,6]])
x2 = np.array([5,6])
print(x1,"\n")
print(x2)

[[1 2]
 [3 4]
 [5 6]] 

[5 6]


In [28]:
# addition of matrices
print(np.add(x1,x2), "\n")
print(x1+x2)

[[ 6  8]
 [ 8 10]
 [10 12]] 

[[ 6  8]
 [ 8 10]
 [10 12]]


In [29]:
# subtraction of matrices
print(np.subtract(x1,x2), "\n")
print(x1-x2)

[[-4 -4]
 [-2 -2]
 [ 0  0]] 

[[-4 -4]
 [-2 -2]
 [ 0  0]]


In [30]:
# element wise multiplication
print(np.multiply(x1,x2))

[[ 5 12]
 [15 24]
 [25 36]]


In [31]:
# matrix multiplication
print(np.dot(x1,x2))

[17 39 61]
